// Generated by CoffeeScript 1.9.3
(function() {
  var Slack, autoMark, autoReconnect, slack, token;
	var WebSocketServer = require('ws').Server
	  , wss = new WebSocketServer({port: process.env.PORT || 5000});

  // Grab add-ons
  var osu = require('./osu.js');
  var quotes = require('./quotes.js');
  var scoreKeeper = require('./scoreKeeper.js');
  var yolo = require('./yolo.js');

  Slack = require('..');

  token = process.env.SLACKBOT_TOKEN;

  autoReconnect = true;

  autoMark = true;

  slack = new Slack(token, autoReconnect, autoMark);

  // Set up persistence
  slack.persist = require('./persist.js');
  slack.persist.readPersistFile(function(persistData) {
    slack.data = persistData;
    console.log(slack.data);
  });

  osu(slack);
  quotes(slack);
  scoreKeeper(slack);
  yolo(slack);

  slack.on('open', function() {
    var channel, channels, group, groups, id, messages, unreads;
    channels = [];
    groups = [];
    unreads = slack.getUnreadCount();
    channels = (function() {
      var ref, results;
      ref = slack.channels;
      results = [];
      for (id in ref) {
        channel = ref[id];
        if (channel.is_member) {
          results.push("#" + channel.name);
        }
      }
      return results;
    })();
    groups = (function() {
      var ref, results;
      ref = slack.groups;
      results = [];
      for (id in ref) {
        group = ref[id];
        if (group.is_open && !group.is_archived) {
          results.push(group.name);
        }
      }
      return results;
    })();
		console.log("Process is running on port: " + process.env.PORT);
    console.log("Welcome to Slack. You are @" + slack.self.name + " of " + slack.team.name);
    console.log('You are in: ' + channels.join(', '));
    console.log('As well as: ' + groups.join(', '));
    messages = unreads === 1 ? 'message' : 'messages';
    return console.log("You have " + unreads + " unread " + messages);
  });

  slack.on('error', function(error) {
    return console.error("Error: " + error);
  });

  slack.login();

}).call(this);
