module.exports = function(slackInst) {
  var quotes = [
    "Okay, here's the shot out of the cannon: Oprah, Barbara Walters, your wife. You gotta fuck one, marry one, kill one, go!",
    "We're here to fuck shit up!",
    "You have the voice of an angel. Your voice is like a combination of Fergie and Jesus.",
    "The only reason you're living here is because me and my dad decided that your mom was really hot, and maybe we should just both bang her, and we'll put up with the retard in the meantime.",
    "Look... we can bicker about this night, but what's done is done Dad. Are you guys going to invest or not?",
    "Boats and hoes!",
    "Chewbacca masks!",
    "I would follow you into the mists of Avalon if that's what you mean.",
    "The clown has no penis.",
    "I don't believe in belts.",
    "You know that one scene in The Wizard Of Oz... when the flying monkeys pull apart the scarecrow? That's what it was like.",
    "I witnessed with my eyes your testicles touching my drum set.",
    "I just want you to know I hate you. And so does my dad.",
    "Shut up! You'll wake up my dad and get me grounded.",
    "You and your mom are hilbillies. This is a house of learned doctors.",
    "I'm a curly-headed fuck?",
    "I hope you stay still when you sleep, cause I'm gonna put a rat trap between your legs.",
    "I want you out of my fucking house!",
    "Dad, what are you doing? It's Shark Week.",
    "Yeah, I got 'em from the 70's, 80's and 90's. It's like masturbating in a time machine.",
    "On the count of three, name your favorite dinosaur. Don't even think about it. Just name it. Ready? One, two, three.",
    "Yeah, anyway. My best friend is Ben Affleck...",
    "This is just like Cold Case files! This is just like Cold Case files! This is just like Cold Case files!",
    "That's so funny the first time I heard that, I laughed so hard I fell off my dinosaur.",
    "Well, you're a mama's boy who's too chicken to sing in public!",
    "My drumsets a guy so it makes you gay you fucker!",
    "Look, I wanna' be honest with you. I really need a job. And, I will take any position - as long as it doesn't involve having sex with old ladies for money, or bear traps. Those are my two bugaboos."]

  slackInst.on('message', function(message) {
    var channel, channelError, channelName, errors, response, text, textError, ts, type, typeError, user, userName;
    channel = slackInst.getChannelGroupOrDMByID(message.channel);
    user = slackInst.getUserByID(message.user);
    response = '';
    type = message.type, ts = message.ts, text = message.text;
    channelName = (channel != null ? channel.is_channel : void 0) ? '#' : '';
    channelName = channelName + (channel ? channel.name : 'UNKNOWN_CHANNEL');
    userName = (user != null ? user.name : void 0) != null ? "@" + user.name : "UNKNOWN_USER";
    console.log("Dale Quotes received: " + type + " " + channelName + " " + userName + " " + ts + " \"" + text + "\"");
    if (type === 'message' && (text != null) && (channel != null)) {
      if (text.toLowerCase().indexOf(":dale:") > -1) {
        response = quotes[Math.floor(Math.random()*quotes.length)];
        channel.send(response);
        return console.log("@" + slackInst.self.name + " responded with \"" + response + "\"");
      }
    } else {
      typeError = type !== 'message' ? "unexpected type " + type + "." : null;
      textError = text == null ? 'text was undefined.' : null;
      channelError = channel == null ? 'channel was undefined.' : null;
      errors = [typeError, textError, channelError].filter(function(element) {
        return element !== null;
      }).join(' ');
      return console.log("@" + slackInst.self.name + " could not respond. " + errors);
    }
  });
};

// ---
// generated by coffee-script 1.9.2
