module.exports = function(slackInst) {
  var yolos = ["http://media.giphy.com/media/7CRIsJnZc1yWk/giphy.gif",
	       "http://media.giphy.com/media/SWjCswum5dc0E/giphy.gif",
	       "http://media.giphy.com/media/WA4ayZW0DJJWU/giphy.gif",
	       "http://www.macleans.ca/wp-content/uploads/2012/11/obamabiden_wtt_vhbqy.gif",
	       "http://data.whicdn.com/images/163303862/large.gif",
	       "http://media.giphy.com/media/mSUvTbGmuJ0lO/giphy.gif"]

  slackInst.on('message', function(message) {
    var channel, channelError, channelName, errors, response, text, textError, ts, type, typeError, user, userName;
    channel = slackInst.getChannelGroupOrDMByID(message.channel);
    user = slackInst.getUserByID(message.user);
    response = '';
    type = message.type, ts = message.ts, text = message.text;
    channelName = (channel != null ? channel.is_channel : void 0) ? '#' : '';
    channelName = channelName + (channel ? channel.name : 'UNKNOWN_CHANNEL');
    userName = (user != null ? user.name : void 0) != null ? "@" + user.name : "UNKNOWN_USER";
    console.log("Yolo received: " + type + " " + channelName + " " + userName + " " + ts + " \"" + text + "\"");
    if (type === 'message' && (text != null) && (channel != null)) {
      if (text.toLowerCase().indexOf("yolo") > -1) {
        response = yolos[Math.floor(Math.random()*yolos.length)];
        channel.send(response);
        return console.log("@" + slackInst.self.name + " responded with \"" + response + "\"");
      }
    } else {
      typeError = type !== 'message' ? "unexpected type " + type + "." : null;
      textError = text == null ? 'text was undefined.' : null;
      channelError = channel == null ? 'channel was undefined.' : null;
      errors = [typeError, textError, channelError].filter(function(element) {
        return element !== null;
      }).join(' ');
      return console.log("@" + slackInst.self.name + " could not respond. " + errors);
    }
  });
};

// ---
// generated by coffee-script 1.9.2
